[package]
name = "image-effects"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
wasm-bindgen = "0.2.83"
base64 = "0.13.0"
image = "0.24.4"

[dependencies.web-sys]
version = "0.3.60"
features = ["console"]

